spring.application.name=RentSphere
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/RentSphereSchema?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:rentsphere}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rentsphere123}
jwt.secret=0d1JZmj0UyE8ThIocgNAjtma2VCC8NlDSCMCetHB0b4=
jwt.expiration=86400000
spring.main.allow-circular-references=true
spring.security.user.name=admin
spring.security.user.password=admin123
server.port=8080
paypal.client.id=AVjrgUEWW86WyAYKXGNW-DCnp76-NJcFvP2VonLwQizI4zzlw6LBMm_JkVLdmgIfayLWCSr6o7bkv_VU
paypal.client.secret=EMfTbcSGlGDnShVMKFOnJI4IimFMbcfSGWlsA1Gwb71GMdNIxEpnsTGwlwCsO3LiiWjFJVEqU_FIcOIt
paypal.mode=sandbox
