-- RentSphere demo dataset (small, realistic, hand-planned).
--
-- Load Schema.sql first, then this file:
--   docker compose exec -T mysql mysql -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" RentSphereSchema < Database/Schema.sql
--   docker compose exec -T mysql mysql -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" RentSphereSchema < Backend/src/main/resources/db/seed-demo.sql
--
-- What it contains: 1 listing owner (ADMIN) and 3 tenants, 9 listings across Cairo,
-- New Cairo, 6th of October, Giza, Alexandria and Riyadh with 11 photos, 9 rental
-- requests (5 accepted, 3 pending, 1 rejected), 5 contracts (4 active, 1 completed), one
-- installment row per contract month, 8 favourites and the notifications the services
-- write for those events.
--
-- Every date is relative to the day the file is loaded, so the data never goes stale:
-- leases are always part-way through, no installment is ever past due, and one is always
-- due in three days so the daily reminder job has something to do.
--
-- It lives on the backend classpath because DemoDataResetService reloads it on a schedule
-- when rentsphere.demo.reset-enabled is true (the public demo, where anyone can sign in
-- to the accounts below).
--
-- Demo logins share the password 'RentSphereDemo2026'; password_hash holds the BCrypt
-- digest the API generated, not the plain text.
--   owner   (ADMIN)  nour.elsayed@nilenest.demo
--   tenants          youssef.farouk@mail.demo, salma.abdelnabi@mail.demo,
--                    mariam.elhosseiny@mail.demo
--
-- For load testing use Database/seed-large-dataset.sql instead (100k listings); it
-- truncates first, so running one after the other is safe.

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE notifications;
TRUNCATE TABLE payments;
TRUNCATE TABLE contracts;
TRUNCATE TABLE rental_requests;
TRUNCATE TABLE favorites;
TRUNCATE TABLE property_images;
TRUNCATE TABLE properties;
TRUNCATE TABLE users;
SET FOREIGN_KEY_CHECKS = 1;

SET @today = CURDATE();

-- users
INSERT INTO users (user_id, full_name, email, username, role_name, password_hash, mobile_number, avatar_url, is_active, created_at, updated_at) VALUES
  (1, 'Nour El-Sayed', 'nour.elsayed@nilenest.demo', 'nour.nilenest', 'ADMIN', '$2a$10$cw7X5WA5F7tmiTR6T3A.Zu2D1uKDlpdIwO.VNmwd3cTnXHbsVeboK', '+20 100 552 4118', NULL, 1, TIMESTAMP(@today - INTERVAL 5 MONTH, '09:12:40'), TIMESTAMP(@today - INTERVAL 5 MONTH, '09:12:40')),
  (2, 'Youssef Farouk', 'youssef.farouk@mail.demo', 'yousseff', 'TENANT', '$2a$10$J8J7LWFcHEJAcQMfA90wge2XXvDMgcYjkdiIozfkRscvdSpIzdN3q', '+20 111 738 2064', NULL, 1, TIMESTAMP(@today - INTERVAL 4 MONTH, '18:03:11'), TIMESTAMP(@today - INTERVAL 4 MONTH, '18:03:11')),
  (3, 'Salma Abdel-Nabi', 'salma.abdelnabi@mail.demo', 'salmaa', 'TENANT', '$2a$10$0qweYh6283hiswrTV5Brp.yEybSgRbGz8WXTxTQR7lwYiLlAWObYu', '+20 106 640 9932', NULL, 1, TIMESTAMP(@today - INTERVAL 4 MONTH - INTERVAL 25 DAY, '20:41:57'), TIMESTAMP(@today - INTERVAL 4 MONTH - INTERVAL 25 DAY, '20:41:57')),
  (4, 'Mariam El-Hosseiny', 'mariam.elhosseiny@mail.demo', 'mariamh', 'TENANT', '$2a$10$7sZbPyKrdObyiQ6/FQLYDu0qNYdN..Z7cchY3GzhU7kr4K0OprglW', '+20 122 415 7780', NULL, 1, TIMESTAMP(@today - INTERVAL 3 MONTH + INTERVAL 4 DAY, '11:27:05'), TIMESTAMP(@today - INTERVAL 3 MONTH + INTERVAL 4 DAY, '11:27:05'));

-- properties (is_available = 0 exactly where an ACTIVE contract below holds the listing)
INSERT INTO properties (property_id, owner_id, property_type, title, property_description, price_per_month, city, district, address, latitude, longitude, num_rooms, area_sqm, is_available, created_at, updated_at) VALUES
  (1, 1, 'APARTMENT', 'Sunlit 2-Bedroom Apartment on Degory Street', 'Two bedrooms and a reception on a quiet street in Old Maadi, third floor with lift, a short walk from the Road 9 shops. Furnished, gas and water included.', 650.00, 'Cairo', 'Maadi', '14 Degory Street, Old Maadi', 29.960200, 31.256900, 2, 125.00, 0, TIMESTAMP(@today - INTERVAL 5 MONTH + INTERVAL 2 DAY, '10:15:22'), TIMESTAMP(@today - INTERVAL 5 MONTH + INTERVAL 2 DAY, '10:15:22')),
  (2, 1, 'STUDIO', 'Furnished Studio Steps from the AUC Gate', 'Compact studio in a secured building on 90th Street, fitted kitchenette, balcony, gym and roof access. Utilities metered. Ideal for one person or a couple.', 420.00, 'New Cairo', 'Fifth Settlement', 'Apt 704, Nile Business Park, South 90th Street', 30.019600, 31.499000, 1, 48.00, 1, TIMESTAMP(@today - INTERVAL 5 MONTH + INTERVAL 2 DAY, '10:48:09'), TIMESTAMP(@today - INTERVAL 5 MONTH + INTERVAL 2 DAY, '10:48:09')),
  (3, 1, 'VILLA', 'Family Villa with Private Pool, Palm Hills Extension', 'Detached villa off Wahat Road: four bedrooms, two bathrooms, a landscaped garden and a private pool. Staff quarters, two-car garage, 24-hour compound security.', 1500.00, '6th of October', 'Palm Hills', 'Villa 14, Palm Hills Extension, Wahat Road', 29.966800, 30.943300, 4, 320.00, 0, TIMESTAMP(@today - INTERVAL 5 MONTH + INTERVAL 9 DAY, '16:30:44'), TIMESTAMP(@today - INTERVAL 5 MONTH + INTERVAL 9 DAY, '16:30:44')),
  (4, 1, 'APARTMENT', 'Three Bedrooms with an Unbroken View of the Pyramids', 'Corner apartment on the top floor of a small building in Hadayek El Ahram. West-facing terrace, three bedrooms, two bathrooms, parking in the basement.', 900.00, 'Giza', 'Hadayek El Ahram', 'Apt 12, Gate 1, Hadayek El Ahram', 29.987000, 31.103500, 3, 165.00, 1, TIMESTAMP(@today - INTERVAL 4 MONTH, '12:05:31'), TIMESTAMP(@today - INTERVAL 4 MONTH, '12:05:31')),
  (5, 1, 'APARTMENT', 'Sea-View Apartment on the Alexandria Corniche', 'Reception and two bedrooms facing the Mediterranean in Roushdy, refitted last summer, two balconies, a storage room, and the tram stop one block inland.', 780.00, 'Alexandria', 'Roushdy', '17 El Geish Road, Roushdy', 31.228500, 29.951200, 2, 140.00, 0, TIMESTAMP(@today - INTERVAL 4 MONTH + INTERVAL 6 DAY, '09:52:18'), TIMESTAMP(@today - INTERVAL 4 MONTH + INTERVAL 6 DAY, '09:52:18')),
  (6, 1, 'STUDIO', 'Quiet Studio behind Bibliotheca Alexandrina', 'Single room with kitchenette and bathroom in a restored El Shatby building, four minutes on foot from the library and the corniche. Bills excluded.', 300.00, 'Alexandria', 'El Shatby', '5 Port Said Street, El Shatby', 31.207600, 29.911600, 1, 40.00, 1, TIMESTAMP(@today - INTERVAL 4 MONTH + INTERVAL 6 DAY, '10:20:03'), TIMESTAMP(@today - INTERVAL 4 MONTH + INTERVAL 6 DAY, '10:20:03')),
  (7, 1, 'OFFICE', 'Open-Plan Office Suite in Smart Village', 'Fourth-floor suite with two meeting rooms and a server corner, 210 sqm, raised floor, backup power and two parking badges. Fit-out available on request.', 1200.00, 'Giza', 'Smart Village', 'Building B2, Floor 4, Km 28 Cairo-Alexandria Desert Road', 30.071100, 31.017500, 3, 210.00, 1, TIMESTAMP(@today - INTERVAL 5 MONTH + INTERVAL 10 DAY, '14:11:50'), TIMESTAMP(@today - INTERVAL 5 MONTH + INTERVAL 10 DAY, '14:11:50')),
  (8, 1, 'APARTMENT', 'Furnished Two-Bedroom in Al Malqa, North Riyadh', 'Bright apartment in a gated compound in Al Malqa: master bedroom with en-suite, second bedroom, central AC, residents gym and a shaded childrens play area.', 930.00, 'Riyadh', 'Al Malqa', 'Building 22, Wadi Hajr Street, Al Malqa', 24.803500, 46.613000, 2, 110.00, 1, TIMESTAMP(@today - INTERVAL 3 MONTH, '13:40:27'), TIMESTAMP(@today - INTERVAL 3 MONTH, '13:40:27')),
  (9, 1, 'DUPLEX', 'Modern Duplex with Private Garden in North Katameya', 'Two-storey duplex in a small compound: reception and kitchen on the ground floor, three bedrooms upstairs, a roof terrace, and a fenced garden with an automatic gate.', 1100.00, 'New Cairo', 'Katameya', 'Unit 9, North Katameya Compound', 29.993900, 31.411700, 3, 190.00, 0, TIMESTAMP(@today - INTERVAL 2 MONTH + INTERVAL 3 DAY, '17:22:36'), TIMESTAMP(@today - INTERVAL 2 MONTH + INTERVAL 3 DAY, '17:22:36'));

-- property_images (files ship with the frontend under public/uploads/demo)
INSERT INTO property_images (property_img_id, property_id, image_url, is_cover, uploaded_at) VALUES
  (1, 1, '/uploads/demo/maadi-living.jpg', 1, TIMESTAMP(@today - INTERVAL 5 MONTH + INTERVAL 2 DAY, '10:15:22')),
  (2, 1, '/uploads/demo/maadi-kitchen.jpg', 0, TIMESTAMP(@today - INTERVAL 5 MONTH + INTERVAL 2 DAY, '10:15:22')),
  (3, 1, '/uploads/demo/maadi-bedroom.jpg', 0, TIMESTAMP(@today - INTERVAL 5 MONTH + INTERVAL 2 DAY, '10:15:22')),
  (4, 2, '/uploads/demo/newcairo-studio.jpg', 1, TIMESTAMP(@today - INTERVAL 5 MONTH + INTERVAL 2 DAY, '10:48:09')),
  (5, 3, '/uploads/demo/october-villa.jpg', 1, TIMESTAMP(@today - INTERVAL 5 MONTH + INTERVAL 9 DAY, '16:30:44')),
  (6, 4, '/uploads/demo/sheikhzayed-view.jpg', 1, TIMESTAMP(@today - INTERVAL 4 MONTH, '12:05:31')),
  (7, 5, '/uploads/demo/corniche-sea.jpg', 1, TIMESTAMP(@today - INTERVAL 4 MONTH + INTERVAL 6 DAY, '09:52:18')),
  (8, 6, '/uploads/demo/alex-studio.jpg', 1, TIMESTAMP(@today - INTERVAL 4 MONTH + INTERVAL 6 DAY, '10:20:03')),
  (9, 7, '/uploads/demo/smartvillage-office.jpg', 1, TIMESTAMP(@today - INTERVAL 5 MONTH + INTERVAL 10 DAY, '14:11:50')),
  (10, 8, '/uploads/demo/riyadh-malqa.jpg', 1, TIMESTAMP(@today - INTERVAL 3 MONTH, '13:40:27')),
  (11, 9, '/uploads/demo/heliopolis-duplex.jpg', 1, TIMESTAMP(@today - INTERVAL 2 MONTH + INTERVAL 3 DAY, '17:22:36'));

-- favorites
INSERT INTO favorites (tenant_id, property_id, saved_at) VALUES
  (2, 2, TIMESTAMP(@today - INTERVAL 9 DAY, '21:00:00')),
  (2, 4, TIMESTAMP(@today - INTERVAL 8 DAY, '21:01:00')),
  (2, 7, TIMESTAMP(@today - INTERVAL 30 DAY, '21:02:00')),
  (3, 1, TIMESTAMP(@today - INTERVAL 70 DAY, '21:03:00')),
  (3, 3, TIMESTAMP(@today - INTERVAL 45 DAY, '21:04:00')),
  (3, 9, TIMESTAMP(@today - INTERVAL 11 DAY, '21:05:00')),
  (4, 5, TIMESTAMP(@today - INTERVAL 75 DAY, '21:06:00')),
  (4, 6, TIMESTAMP(@today - INTERVAL 40 DAY, '21:07:00'));

-- rental_requests
INSERT INTO rental_requests (rental_req_id, property_id, tenant_id, message, desired_start, desired_months, req_status, reviewed_at, created_at, updated_at) VALUES
  (1, 1, 2, 'Moving to Maadi with my wife for a new job nearby. We would like to renew for a second year if the rent holds.', @today - INTERVAL 3 MONTH + INTERVAL 12 DAY, 12, 'ACCEPTED', TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY, '10:02:17'), TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (2, 2, 2, 'Single tenant, working remotely, no pets. Could view any weekday evening.', @today + INTERVAL 21 DAY, 12, 'PENDING', NULL, TIMESTAMP(@today - INTERVAL 3 DAY, '19:14:08'), TIMESTAMP(@today - INTERVAL 3 DAY, '19:14:08')),
  (3, 6, 2, 'Student at Alexandria University, looking for a one-semester let close to campus.', @today + INTERVAL 25 DAY, 6, 'REJECTED', TIMESTAMP((@today - INTERVAL 20 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(@today - INTERVAL 20 DAY, '15:33:02'), TIMESTAMP((@today - INTERVAL 20 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (4, 3, 3, 'Family of four with two children, references from a previous tenancy in Sheikh Zayed available.', @today - INTERVAL 1 MONTH + INTERVAL 20 DAY, 12, 'ACCEPTED', TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY, '14:26:39'), TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (5, 4, 3, 'Looking for a long lease for my parents. They do not need furnishing.', @today + INTERVAL 30 DAY, 12, 'PENDING', NULL, TIMESTAMP(@today - INTERVAL 2 DAY, '08:45:51'), TIMESTAMP(@today - INTERVAL 2 DAY, '08:45:51')),
  (6, 8, 3, 'Secondment in Riyadh starting next month, would need the furnished option.', @today + INTERVAL 34 DAY, 9, 'PENDING', NULL, TIMESTAMP(@today - INTERVAL 1 DAY, '22:07:19'), TIMESTAMP(@today - INTERVAL 1 DAY, '22:07:19')),
  (7, 5, 4, 'I work at the Bibliotheca and would take a sea view over a bigger flat.', @today - INTERVAL 2 MONTH + INTERVAL 3 DAY, 12, 'ACCEPTED', TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY, '09:18:55'), TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (8, 9, 4, 'Two adults and a small dog, happy to pay three months up front.', @today + INTERVAL 14 DAY, 6, 'ACCEPTED', TIMESTAMP((@today - INTERVAL 6 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(@today - INTERVAL 6 DAY, '12:31:44'), TIMESTAMP((@today - INTERVAL 6 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (9, 7, 3, 'Short let for a four-person project team while our own office is being fitted out.', @today - INTERVAL 4 MONTH - INTERVAL 5 DAY, 3, 'ACCEPTED', TIMESTAMP(((@today - INTERVAL 4 MONTH - INTERVAL 5 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP((@today - INTERVAL 4 MONTH - INTERVAL 5 DAY) - INTERVAL 9 DAY, '11:47:20'), TIMESTAMP(((@today - INTERVAL 4 MONTH - INTERVAL 5 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'));

-- contracts (rent_amount is the listing price, end_date = start_date + duration)
INSERT INTO contracts (contract_id, rental_request_id, property_id, owner_id, tenant_id, contract_status, rent_amount, duration_months, start_date, end_date, pdf_url, notes, created_at, updated_at) VALUES
  (1, 1, 1, 1, 2, 'ACTIVE', 650.00, 12, @today - INTERVAL 3 MONTH + INTERVAL 12 DAY, (@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) + INTERVAL 12 MONTH, NULL, 'Auto-generated contract after rental approval', TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (2, 4, 3, 1, 3, 'ACTIVE', 1500.00, 12, @today - INTERVAL 1 MONTH + INTERVAL 20 DAY, (@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) + INTERVAL 12 MONTH, NULL, 'Auto-generated contract after rental approval', TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (3, 7, 5, 1, 4, 'ACTIVE', 780.00, 12, @today - INTERVAL 2 MONTH + INTERVAL 3 DAY, (@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) + INTERVAL 12 MONTH, NULL, 'Auto-generated contract after rental approval', TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (4, 8, 9, 1, 4, 'ACTIVE', 1100.00, 6, @today + INTERVAL 14 DAY, (@today + INTERVAL 14 DAY) + INTERVAL 6 MONTH, NULL, 'Auto-generated contract after rental approval', TIMESTAMP((@today - INTERVAL 6 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP((@today - INTERVAL 6 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (5, 9, 7, 1, 3, 'COMPLETED', 1200.00, 3, @today - INTERVAL 4 MONTH - INTERVAL 5 DAY, (@today - INTERVAL 4 MONTH - INTERVAL 5 DAY) + INTERVAL 3 MONTH, NULL, 'Auto-generated contract after rental approval', TIMESTAMP(((@today - INTERVAL 4 MONTH - INTERVAL 5 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 4 MONTH - INTERVAL 5 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'));

-- payments (one per contract month; settled rows carry the amount and a reference)
INSERT INTO payments (payment_id, contract_id, payment_status, installment_no, due_date, paid_date, amount_due, amount_paid, transaction_ref, notes, created_at, updated_at) VALUES
  (1, 1, 'PAID', 1, @today - INTERVAL 3 MONTH + INTERVAL 12 DAY, TIMESTAMP((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 2 DAY, '09:18:00'), 650.00, 650.00, 'CC-PAY-D787669E', NULL, TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 2 DAY, '09:18:00')),
  (2, 1, 'PAID', 2, (@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) + INTERVAL 1 MONTH, TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) + INTERVAL 1 MONTH) - INTERVAL 2 DAY, '09:19:00'), 650.00, 650.00, 'CC-PAY-B8A26452', NULL, TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) + INTERVAL 1 MONTH) - INTERVAL 2 DAY, '09:19:00')),
  (3, 1, 'PAID', 3, (@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) + INTERVAL 2 MONTH, TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) + INTERVAL 2 MONTH) - INTERVAL 2 DAY, '09:20:00'), 650.00, 650.00, 'CC-PAY-62D5D828', NULL, TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) + INTERVAL 2 MONTH) - INTERVAL 2 DAY, '09:20:00')),
  (4, 1, 'PENDING', 4, (@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) + INTERVAL 3 MONTH, NULL, 650.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (5, 1, 'PENDING', 5, (@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) + INTERVAL 4 MONTH, NULL, 650.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (6, 1, 'PENDING', 6, (@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) + INTERVAL 5 MONTH, NULL, 650.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (7, 1, 'PENDING', 7, (@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) + INTERVAL 6 MONTH, NULL, 650.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (8, 1, 'PENDING', 8, (@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) + INTERVAL 7 MONTH, NULL, 650.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (9, 1, 'PENDING', 9, (@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) + INTERVAL 8 MONTH, NULL, 650.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (10, 1, 'PENDING', 10, (@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) + INTERVAL 9 MONTH, NULL, 650.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (11, 1, 'PENDING', 11, (@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) + INTERVAL 10 MONTH, NULL, 650.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (12, 1, 'PENDING', 12, (@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) + INTERVAL 11 MONTH, NULL, 650.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (13, 2, 'PAID', 1, @today - INTERVAL 1 MONTH + INTERVAL 20 DAY, TIMESTAMP((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 2 DAY, '09:25:00'), 1500.00, 1500.00, 'CC-PAY-6A057B01', NULL, TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 2 DAY, '09:25:00')),
  (14, 2, 'PENDING', 2, (@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) + INTERVAL 1 MONTH, NULL, 1500.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (15, 2, 'PENDING', 3, (@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) + INTERVAL 2 MONTH, NULL, 1500.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (16, 2, 'PENDING', 4, (@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) + INTERVAL 3 MONTH, NULL, 1500.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (17, 2, 'PENDING', 5, (@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) + INTERVAL 4 MONTH, NULL, 1500.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (18, 2, 'PENDING', 6, (@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) + INTERVAL 5 MONTH, NULL, 1500.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (19, 2, 'PENDING', 7, (@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) + INTERVAL 6 MONTH, NULL, 1500.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (20, 2, 'PENDING', 8, (@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) + INTERVAL 7 MONTH, NULL, 1500.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (21, 2, 'PENDING', 9, (@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) + INTERVAL 8 MONTH, NULL, 1500.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (22, 2, 'PENDING', 10, (@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) + INTERVAL 9 MONTH, NULL, 1500.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (23, 2, 'PENDING', 11, (@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) + INTERVAL 10 MONTH, NULL, 1500.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (24, 2, 'PENDING', 12, (@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) + INTERVAL 11 MONTH, NULL, 1500.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (25, 3, 'PAID', 1, @today - INTERVAL 2 MONTH + INTERVAL 3 DAY, TIMESTAMP((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 2 DAY, '09:32:00'), 780.00, 780.00, 'CC-PAY-3EAD601F', NULL, TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 2 DAY, '09:32:00')),
  (26, 3, 'PAID', 2, (@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) + INTERVAL 1 MONTH, TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) + INTERVAL 1 MONTH) - INTERVAL 2 DAY, '09:33:00'), 780.00, 780.00, 'CC-PAY-809393A5', NULL, TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) + INTERVAL 1 MONTH) - INTERVAL 2 DAY, '09:33:00')),
  (27, 3, 'PENDING', 3, (@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) + INTERVAL 2 MONTH, NULL, 780.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (28, 3, 'PENDING', 4, (@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) + INTERVAL 3 MONTH, NULL, 780.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (29, 3, 'PENDING', 5, (@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) + INTERVAL 4 MONTH, NULL, 780.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (30, 3, 'PENDING', 6, (@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) + INTERVAL 5 MONTH, NULL, 780.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (31, 3, 'PENDING', 7, (@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) + INTERVAL 6 MONTH, NULL, 780.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (32, 3, 'PENDING', 8, (@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) + INTERVAL 7 MONTH, NULL, 780.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (33, 3, 'PENDING', 9, (@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) + INTERVAL 8 MONTH, NULL, 780.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (34, 3, 'PENDING', 10, (@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) + INTERVAL 9 MONTH, NULL, 780.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (35, 3, 'PENDING', 11, (@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) + INTERVAL 10 MONTH, NULL, 780.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (36, 3, 'PENDING', 12, (@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) + INTERVAL 11 MONTH, NULL, 780.00, 0.00, NULL, NULL, TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (37, 4, 'PAID', 1, @today + INTERVAL 14 DAY, TIMESTAMP(((@today - INTERVAL 6 DAY) + INTERVAL 2 DAY), '18:21:00'), 1100.00, 1100.00, 'CC-PAY-FA2A92CB', NULL, TIMESTAMP((@today - INTERVAL 6 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 6 DAY) + INTERVAL 2 DAY), '18:21:00')),
  (38, 4, 'PAID', 2, (@today + INTERVAL 14 DAY) + INTERVAL 1 MONTH, TIMESTAMP(((@today - INTERVAL 6 DAY) + INTERVAL 2 DAY), '18:22:00'), 1100.00, 1100.00, 'CC-PAY-A3648566', NULL, TIMESTAMP((@today - INTERVAL 6 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 6 DAY) + INTERVAL 2 DAY), '18:22:00')),
  (39, 4, 'PAID', 3, (@today + INTERVAL 14 DAY) + INTERVAL 2 MONTH, TIMESTAMP(((@today - INTERVAL 6 DAY) + INTERVAL 2 DAY), '18:23:00'), 1100.00, 1100.00, 'CC-PAY-E6F085D0', NULL, TIMESTAMP((@today - INTERVAL 6 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 6 DAY) + INTERVAL 2 DAY), '18:23:00')),
  (40, 4, 'PENDING', 4, (@today + INTERVAL 14 DAY) + INTERVAL 3 MONTH, NULL, 1100.00, 0.00, NULL, NULL, TIMESTAMP((@today - INTERVAL 6 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP((@today - INTERVAL 6 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (41, 4, 'PENDING', 5, (@today + INTERVAL 14 DAY) + INTERVAL 4 MONTH, NULL, 1100.00, 0.00, NULL, NULL, TIMESTAMP((@today - INTERVAL 6 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP((@today - INTERVAL 6 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (42, 4, 'PENDING', 6, (@today + INTERVAL 14 DAY) + INTERVAL 5 MONTH, NULL, 1100.00, 0.00, NULL, NULL, TIMESTAMP((@today - INTERVAL 6 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP((@today - INTERVAL 6 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (43, 5, 'PAID', 1, @today - INTERVAL 4 MONTH - INTERVAL 5 DAY, TIMESTAMP((@today - INTERVAL 4 MONTH - INTERVAL 5 DAY) - INTERVAL 2 DAY, '09:46:00'), 1200.00, 1200.00, 'CC-PAY-377EB704', NULL, TIMESTAMP(((@today - INTERVAL 4 MONTH - INTERVAL 5 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP((@today - INTERVAL 4 MONTH - INTERVAL 5 DAY) - INTERVAL 2 DAY, '09:46:00')),
  (44, 5, 'PAID', 2, (@today - INTERVAL 4 MONTH - INTERVAL 5 DAY) + INTERVAL 1 MONTH, TIMESTAMP(((@today - INTERVAL 4 MONTH - INTERVAL 5 DAY) + INTERVAL 1 MONTH) - INTERVAL 2 DAY, '09:47:00'), 1200.00, 1200.00, 'CC-PAY-DCE00DB2', NULL, TIMESTAMP(((@today - INTERVAL 4 MONTH - INTERVAL 5 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 4 MONTH - INTERVAL 5 DAY) + INTERVAL 1 MONTH) - INTERVAL 2 DAY, '09:47:00')),
  (45, 5, 'PAID', 3, (@today - INTERVAL 4 MONTH - INTERVAL 5 DAY) + INTERVAL 2 MONTH, TIMESTAMP(((@today - INTERVAL 4 MONTH - INTERVAL 5 DAY) + INTERVAL 2 MONTH) - INTERVAL 2 DAY, '09:48:00'), 1200.00, 1200.00, 'CC-PAY-77AB6F41', NULL, TIMESTAMP(((@today - INTERVAL 4 MONTH - INTERVAL 5 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00'), TIMESTAMP(((@today - INTERVAL 4 MONTH - INTERVAL 5 DAY) + INTERVAL 2 MONTH) - INTERVAL 2 DAY, '09:48:00'));

-- notifications (same titles and bodies the services produce)
INSERT INTO notifications (noti_id, recipient_id, notification_type, title, body, is_read, created_at) VALUES
  (1, 1, 'NEW_REQUEST', 'New request #1 for property #1', CONCAT('A tenant requested this property for 12 months starting ', DATE_FORMAT(@today - INTERVAL 3 MONTH + INTERVAL 12 DAY, '%Y-%m-%d'), '.'), 1, TIMESTAMP((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY, '10:02:17')),
  (2, 1, 'NEW_REQUEST', 'New request #2 for property #2', CONCAT('A tenant requested this property for 12 months starting ', DATE_FORMAT(@today + INTERVAL 21 DAY, '%Y-%m-%d'), '.'), 0, TIMESTAMP(@today - INTERVAL 3 DAY, '19:14:08')),
  (3, 1, 'NEW_REQUEST', 'New request #3 for property #6', CONCAT('A tenant requested this property for 6 months starting ', DATE_FORMAT(@today + INTERVAL 25 DAY, '%Y-%m-%d'), '.'), 1, TIMESTAMP(@today - INTERVAL 20 DAY, '15:33:02')),
  (4, 1, 'NEW_REQUEST', 'New request #4 for property #3', CONCAT('A tenant requested this property for 12 months starting ', DATE_FORMAT(@today - INTERVAL 1 MONTH + INTERVAL 20 DAY, '%Y-%m-%d'), '.'), 1, TIMESTAMP((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY, '14:26:39')),
  (5, 1, 'NEW_REQUEST', 'New request #5 for property #4', CONCAT('A tenant requested this property for 12 months starting ', DATE_FORMAT(@today + INTERVAL 30 DAY, '%Y-%m-%d'), '.'), 0, TIMESTAMP(@today - INTERVAL 2 DAY, '08:45:51')),
  (6, 1, 'NEW_REQUEST', 'New request #6 for property #8', CONCAT('A tenant requested this property for 9 months starting ', DATE_FORMAT(@today + INTERVAL 34 DAY, '%Y-%m-%d'), '.'), 0, TIMESTAMP(@today - INTERVAL 1 DAY, '22:07:19')),
  (7, 1, 'NEW_REQUEST', 'New request #7 for property #5', CONCAT('A tenant requested this property for 12 months starting ', DATE_FORMAT(@today - INTERVAL 2 MONTH + INTERVAL 3 DAY, '%Y-%m-%d'), '.'), 1, TIMESTAMP((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY, '09:18:55')),
  (8, 1, 'NEW_REQUEST', 'New request #8 for property #9', CONCAT('A tenant requested this property for 6 months starting ', DATE_FORMAT(@today + INTERVAL 14 DAY, '%Y-%m-%d'), '.'), 1, TIMESTAMP(@today - INTERVAL 6 DAY, '12:31:44')),
  (9, 1, 'NEW_REQUEST', 'New request #9 for property #7', CONCAT('A tenant requested this property for 3 months starting ', DATE_FORMAT(@today - INTERVAL 4 MONTH - INTERVAL 5 DAY, '%Y-%m-%d'), '.'), 1, TIMESTAMP((@today - INTERVAL 4 MONTH - INTERVAL 5 DAY) - INTERVAL 9 DAY, '11:47:20')),
  (10, 2, 'REQUEST_ACCEPTED', 'Rental request #1 accepted', 'Your request was accepted and the rental contract is now active.', 1, TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (11, 2, 'REQUEST_REJECTED', 'Rental request #3 rejected', 'The owner of this property declined your rental request.', 0, TIMESTAMP((@today - INTERVAL 20 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (12, 3, 'REQUEST_ACCEPTED', 'Rental request #4 accepted', 'Your request was accepted and the rental contract is now active.', 1, TIMESTAMP(((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (13, 4, 'REQUEST_ACCEPTED', 'Rental request #7 accepted', 'Your request was accepted and the rental contract is now active.', 1, TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (14, 4, 'REQUEST_ACCEPTED', 'Rental request #8 accepted', 'Your request was accepted and the rental contract is now active.', 1, TIMESTAMP((@today - INTERVAL 6 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (15, 3, 'REQUEST_ACCEPTED', 'Rental request #9 accepted', 'Your request was accepted and the rental contract is now active.', 1, TIMESTAMP(((@today - INTERVAL 4 MONTH - INTERVAL 5 DAY) - INTERVAL 9 DAY) + INTERVAL 2 DAY, '18:05:00')),
  (16, 2, 'PAYMENT_RECEIVED', 'Payment received: contract #1, installment #1', 'Your payment of $650.00 for installment #1 on contract #1 was successfully processed via Credit Card (CC-PAY-D787669E).', 1, TIMESTAMP((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) - INTERVAL 2 DAY, '09:18:00')),
  (17, 2, 'PAYMENT_RECEIVED', 'Payment received: contract #1, installment #2', 'Your payment of $650.00 for installment #2 on contract #1 was successfully processed via Credit Card (CC-PAY-B8A26452).', 1, TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) + INTERVAL 1 MONTH) - INTERVAL 2 DAY, '09:19:00')),
  (18, 2, 'PAYMENT_RECEIVED', 'Payment received: contract #1, installment #3', 'Your payment of $650.00 for installment #3 on contract #1 was successfully processed via Credit Card (CC-PAY-62D5D828).', 1, TIMESTAMP(((@today - INTERVAL 3 MONTH + INTERVAL 12 DAY) + INTERVAL 2 MONTH) - INTERVAL 2 DAY, '09:20:00')),
  (19, 3, 'PAYMENT_RECEIVED', 'Payment received: contract #2, installment #1', 'Your payment of $1500.00 for installment #1 on contract #2 was successfully processed via Credit Card (CC-PAY-6A057B01).', 1, TIMESTAMP((@today - INTERVAL 1 MONTH + INTERVAL 20 DAY) - INTERVAL 2 DAY, '09:25:00')),
  (20, 4, 'PAYMENT_RECEIVED', 'Payment received: contract #3, installment #1', 'Your payment of $780.00 for installment #1 on contract #3 was successfully processed via Credit Card (CC-PAY-3EAD601F).', 1, TIMESTAMP((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) - INTERVAL 2 DAY, '09:32:00')),
  (21, 4, 'PAYMENT_RECEIVED', 'Payment received: contract #3, installment #2', 'Your payment of $780.00 for installment #2 on contract #3 was successfully processed via Credit Card (CC-PAY-809393A5).', 1, TIMESTAMP(((@today - INTERVAL 2 MONTH + INTERVAL 3 DAY) + INTERVAL 1 MONTH) - INTERVAL 2 DAY, '09:33:00')),
  (22, 4, 'PAYMENT_RECEIVED', 'Payment received: contract #4, installment #1', 'Your payment of $1100.00 for installment #1 on contract #4 was successfully processed via Credit Card (CC-PAY-FA2A92CB).', 1, TIMESTAMP(((@today - INTERVAL 6 DAY) + INTERVAL 2 DAY), '18:21:00')),
  (23, 4, 'PAYMENT_RECEIVED', 'Payment received: contract #4, installment #2', 'Your payment of $1100.00 for installment #2 on contract #4 was successfully processed via Credit Card (CC-PAY-A3648566).', 1, TIMESTAMP(((@today - INTERVAL 6 DAY) + INTERVAL 2 DAY), '18:22:00')),
  (24, 4, 'PAYMENT_RECEIVED', 'Payment received: contract #4, installment #3', 'Your payment of $1100.00 for installment #3 on contract #4 was successfully processed via Credit Card (CC-PAY-E6F085D0).', 1, TIMESTAMP(((@today - INTERVAL 6 DAY) + INTERVAL 2 DAY), '18:23:00')),
  (25, 3, 'PAYMENT_RECEIVED', 'Payment received: contract #5, installment #1', 'Your payment of $1200.00 for installment #1 on contract #5 was successfully processed via Credit Card (CC-PAY-377EB704).', 1, TIMESTAMP((@today - INTERVAL 4 MONTH - INTERVAL 5 DAY) - INTERVAL 2 DAY, '09:46:00')),
  (26, 3, 'PAYMENT_RECEIVED', 'Payment received: contract #5, installment #2', 'Your payment of $1200.00 for installment #2 on contract #5 was successfully processed via Credit Card (CC-PAY-DCE00DB2).', 1, TIMESTAMP(((@today - INTERVAL 4 MONTH - INTERVAL 5 DAY) + INTERVAL 1 MONTH) - INTERVAL 2 DAY, '09:47:00')),
  (27, 3, 'PAYMENT_RECEIVED', 'Payment received: contract #5, installment #3', 'Your payment of $1200.00 for installment #3 on contract #5 was successfully processed via Credit Card (CC-PAY-77AB6F41).', 1, TIMESTAMP(((@today - INTERVAL 4 MONTH - INTERVAL 5 DAY) + INTERVAL 2 MONTH) - INTERVAL 2 DAY, '09:48:00')),
  (28, 3, 'CONTRACT_COMPLETED', 'Contract #5 completed', 'Contract #5 has concluded. All installments have been fully paid and the lease term has expired.', 1, TIMESTAMP(((@today - INTERVAL 4 MONTH - INTERVAL 5 DAY) + INTERVAL 3 MONTH) + INTERVAL 1 DAY, '09:00:00'));
